/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Anang Kur
 */
public class MenuPasienInap extends javax.swing.JFrame {

    /**
     * Creates new form MenuPasienInap
     */
    public MenuPasienInap() {
        initComponents();
    }

    public JButton getButtonDeletePasienInap() {
        return buttonDeletePasienInap;
    }

    public JButton getButtonKembaliPasienInap() {
        return buttonKembaliPasienInap;
    }

    public JButton getButtonTambahPasienInap() {
        return buttonTambahPasienInap;
    }

    public JButton getButtonViewPasienInap() {
        return buttonViewPasienInap;
    }

    public JButton getButtonViewRuanganAvailable() {
        return buttonViewRuanganAvailable;
    }

    
    public void addListener(ActionListener a){
        buttonDeletePasienInap.addActionListener(a);
        buttonViewPasienInap.addActionListener(a);
        buttonTambahPasienInap.addActionListener(a);
        buttonKembaliPasienInap.addActionListener(a);
        buttonViewRuanganAvailable.addActionListener(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonDeletePasienInap = new javax.swing.JButton();
        buttonViewRuanganAvailable = new javax.swing.JButton();
        buttonTambahPasienInap = new javax.swing.JButton();
        buttonViewPasienInap = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttonKembaliPasienInap = new javax.swing.JButton();

        buttonDeletePasienInap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonDeletePasienInap.setText("Delete Pasien Inap");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonViewRuanganAvailable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonViewRuanganAvailable.setText("Cek Ruangan Tersedia");

        buttonTambahPasienInap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonTambahPasienInap.setText("Tambah Pasien Inap");

        buttonViewPasienInap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonViewPasienInap.setText("Lihat Pasien Inap");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Pasien Inap");

        buttonKembaliPasienInap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonKembaliPasienInap.setText("Kembali");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonTambahPasienInap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonViewPasienInap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(buttonViewRuanganAvailable)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(152, 152, 152))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonKembaliPasienInap)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(buttonTambahPasienInap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonViewPasienInap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonViewRuanganAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(buttonKembaliPasienInap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDeletePasienInap;
    private javax.swing.JButton buttonKembaliPasienInap;
    private javax.swing.JButton buttonTambahPasienInap;
    private javax.swing.JButton buttonViewPasienInap;
    private javax.swing.JButton buttonViewRuanganAvailable;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
