/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Anang Kur
 */
public class MenuDokter extends javax.swing.JFrame {

    /**
     * Creates new form MenuDokter
     */
    public MenuDokter() {
        initComponents();
    }

    public JButton getButtonDeleteDokter() {
        return buttonDeleteDokter;
    }

    public JButton getButtonEditDokter() {
        return buttonEditDokter;
    }

    public JButton getButtonInputDokter() {
        return buttonInputDokter;
    }

    public JButton getButtonKembaliDokter() {
        return buttonKembaliDokter;
    }

    public JButton getButtonViewDokter() {
        return buttonViewDokter;
    }
    
    public void addListener(ActionListener a){
        buttonDeleteDokter.addActionListener(a);
        buttonEditDokter.addActionListener(a);
        buttonInputDokter.addActionListener(a);
        buttonKembaliDokter.addActionListener(a);
        buttonViewDokter.addActionListener(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonEditDokter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttonInputDokter = new javax.swing.JButton();
        buttonViewDokter = new javax.swing.JButton();
        buttonDeleteDokter = new javax.swing.JButton();
        buttonKembaliDokter = new javax.swing.JButton();

        buttonEditDokter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonEditDokter.setText("Edit Data Dokter");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Dokter");

        buttonInputDokter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonInputDokter.setText("Input Data Dokter");

        buttonViewDokter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonViewDokter.setText("View Data Dokter");

        buttonDeleteDokter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonDeleteDokter.setText("Search Data Dokter");

        buttonKembaliDokter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonKembaliDokter.setText("Kembali");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(206, 206, 206))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonKembaliDokter))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonDeleteDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonViewDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonInputDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(buttonInputDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonViewDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonDeleteDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(buttonKembaliDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDeleteDokter;
    private javax.swing.JButton buttonEditDokter;
    private javax.swing.JButton buttonInputDokter;
    private javax.swing.JButton buttonKembaliDokter;
    private javax.swing.JButton buttonViewDokter;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
