/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Anang Kur
 */
public class MenuPasien extends javax.swing.JFrame {

    /**
     * Creates new form MenuPasien
     */
    public MenuPasien() {
        initComponents();
    }

    public JButton getButtonDeletePasien() {
        return buttonDeletePasien;
    }

    public JButton getButtonEditPasien() {
        return buttonEditPasien;
    }

    public JButton getButtonInputPasien() {
        return buttonInputPasien;
    }

    public JButton getButtonKembaliPasien() {
        return buttonKembaliPasien;
    }

    public JButton getButtonViewPasien() {
        return buttonViewPasien;
    }
        
    public void addListener(ActionListener a){
        buttonDeletePasien.addActionListener(a);
        buttonEditPasien.addActionListener(a);
        buttonInputPasien.addActionListener(a);
        buttonKembaliPasien.addActionListener(a);
        buttonViewPasien.addActionListener(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonEditPasien = new javax.swing.JButton();
        buttonViewPasien = new javax.swing.JButton();
        buttonDeletePasien = new javax.swing.JButton();
        buttonInputPasien = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttonKembaliPasien = new javax.swing.JButton();

        buttonEditPasien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonEditPasien.setText("Edit Data Pasien");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonViewPasien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonViewPasien.setText("View Data Pasien");

        buttonDeletePasien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonDeletePasien.setText("Search Data Pasien");

        buttonInputPasien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonInputPasien.setText("Input Data Pasien");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Pasien");

        buttonKembaliPasien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonKembaliPasien.setText("Kembali");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 196, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(206, 206, 206))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonKembaliPasien)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(buttonDeletePasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonViewPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonInputPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(buttonInputPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonViewPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonDeletePasien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(buttonKembaliPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDeletePasien;
    private javax.swing.JButton buttonEditPasien;
    private javax.swing.JButton buttonInputPasien;
    private javax.swing.JButton buttonKembaliPasien;
    private javax.swing.JButton buttonViewPasien;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
