/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Anang Kur
 */
public class MenuTambahPasienInap extends javax.swing.JFrame {

    /**
     * Creates new form MenuInputPasienInap
     */
    public MenuTambahPasienInap() {
        initComponents();
    }

    public JButton getBtnBatalTambahPasienInap() {
        return btnBatalTambahPasienInap;
    }

    public JButton getBtnSelesaiTambahPasienInap() {
        return btnSelesaiTambahPasienInap;
    }

    public JTextField getFieldInputCariIdDokterTambahPasienInap() {
        return fieldInputCariIdDokterTambahPasienInap;
    }

    public JTextField getFieldInputCariIdPasienTambahPasienInap() {
        return fieldInputCariIdPasienTambahPasienInap;
    }

    public JTextField getFieldInputCariNoRuanganTambahPasienInap() {
        return fieldInputCariNoRuanganTambahPasienInap;
    }
    
    public void addListener(ActionListener a){
        btnBatalTambahPasienInap.addActionListener(a);
        btnSelesaiTambahPasienInap.addActionListener(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSelesaiTambahPasienInap = new javax.swing.JButton();
        btnBatalTambahPasienInap = new javax.swing.JButton();
        fieldInputCariNoRuanganTambahPasienInap = new javax.swing.JTextField();
        fieldInputCariIdPasienTambahPasienInap = new javax.swing.JTextField();
        fieldInputCariIdDokterTambahPasienInap = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tambah Pasien Inap");

        jLabel2.setText("Nomor Ruangan");

        jLabel3.setText("Id Pasien");

        jLabel4.setText("Id Dokter");

        btnSelesaiTambahPasienInap.setText("Selesai");

        btnBatalTambahPasienInap.setText("Batal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBatalTambahPasienInap)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSelesaiTambahPasienInap))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(33, 33, 33)
                                .addComponent(fieldInputCariIdDokterTambahPasienInap, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(33, 33, 33)
                                .addComponent(fieldInputCariNoRuanganTambahPasienInap, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(34, 34, 34)
                                .addComponent(fieldInputCariIdPasienTambahPasienInap, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldInputCariNoRuanganTambahPasienInap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldInputCariIdPasienTambahPasienInap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fieldInputCariIdDokterTambahPasienInap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelesaiTambahPasienInap)
                    .addComponent(btnBatalTambahPasienInap))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalTambahPasienInap;
    private javax.swing.JButton btnSelesaiTambahPasienInap;
    private javax.swing.JTextField fieldInputCariIdDokterTambahPasienInap;
    private javax.swing.JTextField fieldInputCariIdPasienTambahPasienInap;
    private javax.swing.JTextField fieldInputCariNoRuanganTambahPasienInap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
