/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Anang Kur
 */
public class MenuRuangan extends javax.swing.JFrame {

    /**
     * Creates new form MenuRuangan
     */
    public MenuRuangan() {
        initComponents();
    }

    public JButton getButtonDeleteRuangan() {
        return buttonDeleteRuangan;
    }

    public JButton getButtonEditRuangan() {
        return buttonEditRuangan;
    }

    public JButton getButtonInputRuangan() {
        return buttonInputRuangan;
    }

    public JButton getButtonKembaliRuangan() {
        return buttonKembaliRuangan;
    }

    public JButton getButtonViewRuangan() {
        return buttonViewRuangan;
    }
    
    public void addListener(ActionListener a){
        buttonDeleteRuangan.addActionListener(a);
        buttonEditRuangan.addActionListener(a);
        buttonInputRuangan.addActionListener(a);
        buttonKembaliRuangan.addActionListener(a);
        buttonViewRuangan.addActionListener(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonEditRuangan = new javax.swing.JButton();
        buttonDeleteRuangan = new javax.swing.JButton();
        buttonViewRuangan = new javax.swing.JButton();
        buttonInputRuangan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttonKembaliRuangan = new javax.swing.JButton();

        buttonEditRuangan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonEditRuangan.setText("Edit Data Ruangan");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonDeleteRuangan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonDeleteRuangan.setText("SearchData Ruangan");

        buttonViewRuangan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonViewRuangan.setText("View Data Ruangan");

        buttonInputRuangan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonInputRuangan.setText("Input Data Ruangan");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Ruangan");

        buttonKembaliRuangan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonKembaliRuangan.setText("Kembali");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 188, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(189, 189, 189))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonKembaliRuangan)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonInputRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(buttonDeleteRuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonViewRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(buttonInputRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonViewRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonDeleteRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(buttonKembaliRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDeleteRuangan;
    private javax.swing.JButton buttonEditRuangan;
    private javax.swing.JButton buttonInputRuangan;
    private javax.swing.JButton buttonKembaliRuangan;
    private javax.swing.JButton buttonViewRuangan;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
