/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Anang Kur
 */
public class MenuUtama extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Login
     */
    public MenuUtama() {
        initComponents();
    }

    public JButton getButtonDokter() {
        return buttonDokter;
    }

    public JButton getButtonKeluar() {
        return buttonKeluar;
    }

    public JButton getButtonPasien() {
        return buttonPasien;
    }

    public JButton getButtonPasienInap() {
        return buttonPasienInap;
    }

    public JButton getButtonRuangan() {
        return buttonRuangan;
    }
    
    public void addListener(ActionListener a){
        buttonDokter.addActionListener(a);
        buttonKeluar.addActionListener(a);
        buttonPasien.addActionListener(a);
        buttonPasienInap.addActionListener(a);
        buttonRuangan.addActionListener(a);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPasien = new javax.swing.JButton();
        buttonRuangan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        buttonPasienInap = new javax.swing.JButton();
        buttonDokter = new javax.swing.JButton();
        buttonKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonPasien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonPasien.setText("Pasien");

        buttonRuangan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonRuangan.setText("Ruangan");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Aplikasi Rumah Sakit");

        buttonPasienInap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonPasienInap.setText("Pasien Inap");

        buttonDokter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonDokter.setText("Dokter");

        buttonKeluar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonKeluar.setText("Keluar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonRuangan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPasienInap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPasien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(139, 139, 139))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonKeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(buttonDokter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonPasien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPasienInap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRuangan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(buttonKeluar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDokter;
    private javax.swing.JButton buttonKeluar;
    private javax.swing.JButton buttonPasien;
    private javax.swing.JButton buttonPasienInap;
    private javax.swing.JButton buttonRuangan;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
