/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Anang Kur
 */
public class MenuCariDokter extends javax.swing.JFrame {

    /**
     * Creates new form MenuCariDokter
     */
    public MenuCariDokter() {
        initComponents();
    }

    public JButton getBtnBatalCariDokter() {
        return btnBatalCariDokter;
    }

    public JTextField getFieldCariDokter() {
        return fieldCariDokter;
    }

    public JButton getBtnCariDeleteDokter() {
        return btnCariDeleteDokter;
    }

    public JButton getBtnCariEditDokter() {
        return btnCariEditDokter;
    }
    
    
    public void addListener(ActionListener a){
        btnBatalCariDokter.addActionListener(a);
        btnCariEditDokter.addActionListener(a);
        fieldCariDokter.addActionListener(a);
        btnCariDeleteDokter.addActionListener(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldCariDokter = new javax.swing.JTextField();
        btnCariEditDokter = new javax.swing.JButton();
        btnBatalCariDokter = new javax.swing.JButton();
        btnCariDeleteDokter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cari Dokter");

        jLabel2.setText("Id Dokter");

        btnCariEditDokter.setText("Edit");

        btnBatalCariDokter.setText("Batal");

        btnCariDeleteDokter.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(192, 192, 192))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(57, 57, 57)
                        .addComponent(fieldCariDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBatalCariDokter)
                        .addGap(18, 18, 18)
                        .addComponent(btnCariEditDokter)
                        .addGap(18, 18, 18)
                        .addComponent(btnCariDeleteDokter)
                        .addGap(126, 126, 126))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldCariDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCariEditDokter)
                    .addComponent(btnBatalCariDokter)
                    .addComponent(btnCariDeleteDokter))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalCariDokter;
    private javax.swing.JButton btnCariDeleteDokter;
    private javax.swing.JButton btnCariEditDokter;
    private javax.swing.JTextField fieldCariDokter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
