/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Anang Kur
 */
public class MenuCariRuangan extends javax.swing.JFrame {

    /**
     * Creates new form MenuCariRuangan
     */
    public MenuCariRuangan() {
        initComponents();
    }

    public JButton getBtnBatalCariRuangan() {
        return btnBatalCariRuangan;
    }

    public JButton getBtnCariDeleteRuangan() {
        return btnCariDeleteRuangan;
    }

    public JButton getBtnCariEditRuangan() {
        return btnCariEditRuangan;
    }

    public JButton getBtnCariRuangan() {
        return btnCariRuangan;
    }    

    public JTextField getFieldCariRuangan() {
        return fieldCariRuangan;
    }
   
    public void addListener(ActionListener a){
        btnBatalCariRuangan.addActionListener(a);
        btnCariEditRuangan.addActionListener(a);
        btnCariDeleteRuangan.addActionListener(a);
        btnCariRuangan.addActionListener(a);
        fieldCariRuangan.addActionListener(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldCariRuangan = new javax.swing.JTextField();
        btnBatalCariRuangan = new javax.swing.JButton();
        btnCariEditRuangan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCariDeleteRuangan = new javax.swing.JButton();
        btnCariRuangan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBatalCariRuangan.setText("Batal");

        btnCariEditRuangan.setText("Edit");

        jLabel2.setText("Nomor Ruangan");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cari Ruangan");

        btnCariDeleteRuangan.setText("Delete");

        btnCariRuangan.setText("Lihat Pasien Inap");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2)
                        .addGap(57, 57, 57)
                        .addComponent(fieldCariRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnBatalCariRuangan)
                        .addGap(18, 18, 18)
                        .addComponent(btnCariEditRuangan)
                        .addGap(18, 18, 18)
                        .addComponent(btnCariDeleteRuangan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(btnCariRuangan)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldCariRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCariEditRuangan)
                    .addComponent(btnBatalCariRuangan)
                    .addComponent(btnCariDeleteRuangan))
                .addGap(18, 18, 18)
                .addComponent(btnCariRuangan)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalCariRuangan;
    private javax.swing.JButton btnCariDeleteRuangan;
    private javax.swing.JButton btnCariEditRuangan;
    private javax.swing.JButton btnCariRuangan;
    private javax.swing.JTextField fieldCariRuangan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
